name: Build veh_patch DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1

    - name: Configure CMake
      run: cmake -B build -S . -A x64

    - name: Build
      run: cmake --build build --config Release

    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: veh_patch_dll
        path: build/Release/*.dll
